apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: devopsapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32222

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
  labels:
    app: devopsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      imagePullSecrets:
        - name: jfrog-secret1
      containers:
        - name: devopsapp
          image: myimage
          ports:
            - containerPort: 8080
